baseURL = 'https://jacmoe.github.io/'
languageCode = 'en-us'
title = 'Jacmoes Cyber Soapbox'
publishDir = 'docs'
theme = 'anubis'

paginate = 3

[author]
name = 'Jacob Moena'

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/posts/"
weight = 2

[params]
author = 'Jacob Moena'
description = 'Increasingly interesting'
paginationSinglePost = false
style = 'light-without-switcher'
readMore = true
readNextPosts = 0
copyCodeButton = true
rssAsSocialIcon = true
disableSummary = true
utterancesRepo = 'stuff'
dateFormat = "Monday, Jan 2, 2006"

[[params.social]]
id = 'mastodon'
name = 'jacmoe'
url = 'https://writing.exchange/@jacmoe'

[[params.social]]
id = 'github'
name = 'jacmoe'
url = 'https://github.com/jacmoe/'

[[params.social]]
id = 'reddit'
name = 'jacmoe'
url = 'https://www.reddit.com/user/jacmoe'

[[params.social]]
id = 'facebook'
name = 'jacmoe'
url = 'https://facebook.com/jacmoe/'

[markup.goldmark.renderer]
unsafe = true
