baseURL = 'https://jacmoe.github.io/'
languageCode = 'en-us'
title = 'Jacmoes Cyber Soapbox'
publishDir = 'docs'
theme = 'anubis'

paginate = 3

[author]
name = 'Jacob Moena'

[params]
author = 'Jacob Moena'
description = 'Increasingly interesting'
paginationSinglePost = true
style = 'auto-without-switcher'
readMore = true
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
disableSummary = true

[[params.social]]
id = 'twitter'
name = 'jacmoe'
url = 'https://twitter.com/jacmoe/'

[[params.social]]
id = 'github'
name = 'jacmoe'
url = 'https://github.com/jacmoe/'

[[params.social]]
id = 'facebook'
name = 'jacmoe'
url = 'https://facebook.com/jacmoe/'

[markup.goldmark.renderer]
unsafe = true
