baseURL = "https://jacmoe.github.io/"
languageCode = "en-us"
title = "Jacmoes's Cyber Soapbox"
publishDir = 'docs'
theme = "hugo-ficurinia"

author = "Jacob Moena"
copyright = "Jacob Moena - [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)."

paginate = 5
summaryLength = 30

[params]
    dateFormat = "Monday, Jan 2, 2006"
    description = "Jacmoe's Cyber Soapbox"
    author = "Jacob Moena"
    logo = "/android-chrome-512x512.png"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/android-chrome-512x512.png"
    icon512 = "/android-chrome-512x512.png"
    cactusCommentsSiteName = "jacmoe.github.io"
    cactusCommentsServerName = "cactus.chat"
    cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"


    imageInArticlePreview = true

    enableSearch = true  # enable search page
    searchbarEverywhere = false  # if the searchbar should be shown in every page; requires enableSearch
    searchMenuLink = true  # add a search link to the navigation menu; requires enableSearch
    mobileHamburgerNav = false  # alternative hamburger menu layout for the main nav menu when screen is small

    enableSidebarLayout = true
    tocInSidebar = true  # if the sidebar is enbabled, show the TOC in the sidebar

    enableShareOnFediverse = true

    enableRelatedArticles = false
    relatedArticlesNum = 2 
    forceRedirect = true

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/jacmoe"
        weight = 10
    [[menu.icons]]
        identifier = "facebook"
        name = "Facebook"
        url = "https://facebook.com/jacmoe/"
        weight = 30
    [[menu.icons]]
        identifier = "mastodon"
        name = "Mastodon"
        url = "https://writing.exchange/@jacmoe"
        weight = 40
    [[menu.icons]]
        identifier = "gemini_http"
        name = "Gemini (http mirror)"
        url = "https://jacmoe.pollux.casa/index.gmi"
        weight = 50
    [[menu.icons]]
        identifier = "gemini"
        name = "Gemini"
        url = "gemini://jacmoe.pollux.casa"
        weight = 60


[markup.goldmark.renderer]
unsafe = true
